---
# Add these to dc.yml

- name: "SET NTP SERVER"
  hosts: all
  connection: local
  tasks:
  - nxos_ntp: server=1.2.3.4 key_id=32 prefer=enabled host= {{ inventory_hostname }}
  
- name: "NTP AUTH"
  hosts: all
  connection: local
  tasks:
  - nxos_ntp_auth: state=present key_id=32 md5string=hello trusted_key=true auth_type=encrypt host= {{ inventory_hostname }}
