---
# Add these to dc.yml

- name: "SET NTP SERVER"
  hosts: all
  connection: local
  tasks:
  - nxos_ntp: server=1.2.3.4 key_id=32 prefer=enabled host= {{ inventory_hostname }}
  
- name: "NTP AUTH"
  hosts: all
  connection: local
  tasks:
  - nxos_ntp_auth: state=present key_id=32 md5string=hello trusted_key=true auth_type=encrypt host= {{ inventory_hostname }}
  
- name: "SET NTP SOURCE"
  hosts: all
  connection: local
  ios_config:
    provider: "{{ provider }}"
    lines:
      - "{{ ntp_source }}"
      
- name: "GET NTP CONFIG"
  hosts: all
  connection: local
  ios_config:
    provider: "{{ provider }}"
    commands:
      - "show running-config | include clock timezone"
      - "show running-config | include clock summer-time"
      - "show running-config | include ntp source"
      - "show running-config | include ntp server"
      
- name: "SET TIMEZONE"
  when: "(timezone is defined) and (timezone != get_ntp_config.stdout_lines[0][0])"
  register: set_timezone
  ios_config: 
    provider: "{{ provider }}"
    lines: 
      - "{{ timezone }}"
